apiVersion: v1
kind: Service
metadata:
  name: springboot-web-app-svc
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: springboot-web-app